    
    create table heroi (
       id int8 generated by default as identity,
        idade int4 not null,
        identidade_secreta varchar(60) not null unique,
        nome varchar(60) not null,
        primary key (id)
    );
    
    create table poder (
       id int8 generated by default as identity,
        nome varchar(255) not null,
        heroi_id int8 not null,
        primary key (id)
    );
    
    alter table if exists poder 
       add constraint fk_poder_heroi_id 
       foreign key (heroi_id) 
       references heroi;